---
title: "ESR_filteredOR_visualization"
author: "Yu Deng"
date: "February 23, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
library(reshape2)
result = read.csv('../result/ESR_chisquare_result_updated.csv')
result = result[,-1]
dict = read.csv('P:/projects/new_dataset_peakval_only/ESR/data/icd_ESR-peak_0216-after.csv',sep = '|',header= 0,fileEncoding="UTF-8-BOM")
dict = dict[!duplicated(dict$V1),]
dict = dict[dict$V2!='',]
colnames(dict)[ncol(dict)]='icd9_dsc'
final = merge(result, dict, by.x= 'diagnosis', by.y='V1',all.x=T)
data = final 
data$dx_str = paste(data$diagnosis,data$icd9_dsc,sep=':')
data$dx_str= strtrim(data$dx_str,rep(26,length(data$dx_str)))


df_p = data[,c('dx_str','pval_12','pval_13','pval_14','pval_15')]
df1 = melt(df_p, value.name='p_val')
## OR_12: ratio1/ratio2, (1case/1control)/(2case/2control)
df_or = data[,c('dx_str','OR_12','OR_13','OR_14','OR_15')]
df2= melt(df_or, value.name='OddsRatio')

dd = cbind(df1,df2)
dd= dd[,c('dx_str','variable','p_val',"OddsRatio")]
dd_plot = dd[dd$p_val< 0.05, ]
#set cut-off to only show odds ratio that is high 
dd_plot = dd_plot[abs(log(dd_plot$OddsRatio))>2.2,]
## get diagnosis-hisCRP matrix plot 

dd_plot$OddsRatio = as.character(dd_plot$OddsRatio)
dd_plot$OddsRatio = as.numeric(dd_plot$OddsRatio )
dd_plot$indictor =as.numeric(dd_plot$OddsRatio < 1)
dd_plot[dd_plot$indictor==0,'indictor']='decrease_risk'
dd_plot[dd_plot$indictor==1,'indictor']='increase_risk'
```

## Including Plots

You can also embed plots, for example:

```{r, echo=FALSE,,fig.width=7,fig.height=11}
library(ggplot2)

###dd_plot1 dropped icd with Inf value which means 0 cell counts in that category 
dd_plot1 = dd_plot
dd_plot1 = dd_plot1[dd_plot1$OddsRatio!='Inf',]

###dd_plot include inf value and mark it with a different indictor which will have a different color mark 
dd_plot[dd_plot$OddsRatio=='Inf','indictor'] = 'zero cell count'
dd_plot= dd_plot[order(dd_plot$dx_str),]
dd_plot$dx_str <- factor(dd_plot$dx_str, levels=unique(dd_plot$dx_str))

dd_plot1= dd_plot1[order(dd_plot1$dx_str),]
dd_plot1$dx_str <- factor(dd_plot1$dx_str, levels=unique(dd_plot1$dx_str))


##create p1, p2, which include and exclude 'Inf' value and add color 
p1=ggplot(dd_plot[1:150,], aes(x = variable, y = as.factor(dx_str),color=as.factor(indictor))) + geom_point(aes(size = (as.numeric(1/OddsRatio)))) + scale_size_continuous(range = c(1, 4.2))
p2=ggplot(dd_plot1[1:150,], aes(x = variable, y = as.factor(dx_str),color=as.factor(indictor))) + geom_point(aes(size = (as.numeric(1/OddsRatio)))) + scale_size_continuous(range = c(1, 4.2))
#grid.arrange(p1, p2, nrow = 1)
p1
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
